language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
script: "grunt travis -v && phantomjs test/testRunner.js -v"
notifications:
  email:
    - audica-dev@freelists.org
  on_success: change
  on_failure: always